spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    password: Ww861642669+
    url: jdbc:mysql://192.168.199.105:3306/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#    open-in-view: true
server:
  servlet:
    context-path: /sell

